### ISSUE TITLE
PrusaSlicer Arc Overhang Issues

### ISSUE THREAD

**Issue by iterhating** [nicolai-wachenschwan/Image2STL#1]
I know this is the wrong hub, sorry. I can't find the issues page for the prusaslicer-integrated arc generator [https://github.com/nicolai-wachenschwan/arc-overhang-prusaslicer-integration](url) and barely know how to use github (if at all).
The code fails for me. I did a little digging and looking at the code line 841
`        if "; prusaslicer_config = begin" in line:`

It never enters this block, as demonstrated in my debugging and verified with a search through a virgin .gcode output of prusaslicer 2.3.0, which reveals this string never appears.

What prusaslicer version does this require/what gcode block is it looking for so the syntax searched for can be updated?

**Comment by nicolai-wachenschwan** [comment]
Hey,
no problem!
you can just search your specific gcode file. At the end there should be the full config. Copy some unique content of the first line of that config.
For my tests I used PrusaSlicer 2.5

Thats the problem, when using this specific programming, but it is the fastest...
Will add this in the readme :)
